import { Profile, Property, RentalHistoryItem } from './types';

export const INITIAL_PROFILE: Profile = {
  name: 'Alex Thompson',
  email: 'alex.thompson@example.com',
  avatarUrl: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgG-iejlgpClYnT3HvWHKbYVWGBl3Z647e_vvGXw8wmASFqeyNx0QoTSA76CHi_jmWeSqz9EhKeclYjmfKX7GgHtUokA0RXi8JlEmsBSKi_n2pIXYIR8SccoK-LiKhb2HUULHim3m5BB9Ic163CQqe5cveZWW6Rq4TuwsmAhBu5JSsIlyMdcPltpu7Rl44RsWEloKT-qe1L4QEgg9PVACTFB9O_0ZO5wX68hb-RWnAgYxuT_2LBdtbBWEfX2BLt2TwSSLHbH1vDMM',
  isVerifiedTenant: true,
  memberSinceYear: 2021,
  aboutMe: 'I am a professional working in the tech industry, looking for modern urban living spaces. I value clean, well-maintained properties and have a consistent track record of on-time payments and respectful tenancy. My preferred locations are close to public transit and green spaces.',
  trustScore: 80,
  monthsActive: 38,
  reviewsCount: 24,
  ratingValue: 4.8,
  phone: '+1 (555) 321-4567',
  occupation: 'Senior Software Engineer',
  preferredLocations: ['Downtown', 'Greenwich Village', 'Brooklyn Heights'],
  maxBudget: 3500,
  idVerified: true,
  onTimePayer: true,
  insuranceHolder: true,
};

export const INITIAL_RENTAL_HISTORY: RentalHistoryItem[] = [
  {
    id: 'h1',
    name: 'Skyline Modern Loft',
    dateRange: 'Jan 2023 - Present',
    status: 'Current',
    type: 'apartment',
  },
  {
    id: 'h2',
    name: 'Suburban Garden Villa',
    dateRange: 'Feb 2021 - Dec 2022',
    status: 'Completed',
    type: 'bungalow',
  },
  {
    id: 'h3',
    name: 'Riverside Apartment Complex',
    dateRange: 'May 2019 - Jan 2021',
    status: 'Completed',
    type: 'home',
  },
];

export const PROPERTIES: Property[] = [
  {
    id: 'p1',
    title: 'Skyline Modern Loft',
    type: 'Apartment',
    location: '128 Pearl St, Downtown',
    price: 2800,
    imageUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    reviewsCount: 16,
    landlordName: 'Marcus Vance',
    landlordAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    beds: 2,
    baths: 1,
    sqft: 950,
    description: 'Stunning double-height modern loft situated in the heart of Downtown. Offers dramatic city views, premium concrete finishes, stainless steel appliances, and a beautiful spiral staircase leading to the bedroom. High-speed fiber internet and premium storage spaces included.',
    tags: ['City View', 'Loft Living', 'Pet Friendly'],
    amenities: ['24/7 Doorman', 'Rooftop Terrace', 'Gym', 'Fiber WiFi', 'Bike Storage'],
    verified: true,
  },
  {
    id: 'p2',
    title: 'Suburban Garden Villa',
    type: 'Villa',
    location: '45 Sunset Drive, Beverly Hills',
    price: 4900,
    imageUrl: 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    reviewsCount: 12,
    landlordName: 'Sophia Loren',
    landlordAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    beds: 4,
    baths: 3,
    sqft: 2800,
    description: 'Experience pure tranquillity in this sun-drenched suburban garden villa. Featuring a private pool, landscaped gardens, floor-to-ceiling windows, and top-tier kitchen amenities. Located within walking distance of high-end shopping and award-winning private schools.',
    tags: ['Private Pool', 'Luxury', 'Garden'],
    amenities: ['Private Garden', 'Swimming Pool', 'EV Charger', 'Smart Home', 'Spacious Garage'],
    verified: true,
  },
  {
    id: 'p3',
    title: 'Riverside Apartment Complex',
    type: 'Apartment',
    location: '88 Riverfront Blvd, Hudson Valley',
    price: 2100,
    imageUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    reviewsCount: 22,
    landlordName: 'David Miller',
    landlordAvatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
    beds: 1,
    baths: 1,
    sqft: 720,
    description: 'A cozy but highly efficient unit on the bank of the river. Complete with hard-wood flooring, modular closets, smart thermostats, and deep porcelain baths. The community features 24-hour maintenance services and secure on-site garage parking.',
    tags: ['Waterfront', 'Cozy', 'Eco-Design'],
    amenities: ['River-facing Balcony', 'On-site Parking', 'Concierge Service', 'Co-working Lounge', 'Yoga Studio'],
    verified: true,
  },
  {
    id: 'p4',
    title: 'Coastal Sunset Penthouse',
    type: 'Apartment',
    location: '72 Ocean Drive, Malibu',
    price: 6500,
    imageUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&auto=format&fit=crop&q=80',
    rating: 5.0,
    reviewsCount: 8,
    landlordName: 'Elena Rostova',
    landlordAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80',
    beds: 3,
    baths: 3,
    sqft: 2200,
    description: 'Breathtaking panoramic ocean views await you in this premium Malibu penthouse. Equipped with a private wrap-around terrace, automatic glass doors, chef-certified kitchen equipment, and state-of-the-art security mechanisms. Directly integrated with private beach access.',
    tags: ['Beachfront', 'Penthouse', 'Panoramic Views'],
    amenities: ['Private Beach Access', 'Wrap-around Balcony', 'Wine Cellar', 'Elevator Access', 'Central AC'],
    verified: true,
  },
  {
    id: 'p5',
    title: 'Eco-Friendly Forest Cabin',
    type: 'Villa',
    location: '12 Pines Lane, Portland Woods',
    price: 1800,
    imageUrl: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    reviewsCount: 15,
    landlordName: 'George Forester',
    landlordAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
    beds: 2,
    baths: 1.5,
    sqft: 1100,
    description: 'Get off the grid in this ultra-sustainable cedar forest cabin. Powered by Tesla Solar and featuring rain-water filtration integration, high-tech compost appliances, and a beautiful wood fire stove. Includes stable Starlink satellite high-speed internet.',
    tags: ['Nature Retreat', 'Solar Powered', 'Quiet'],
    amenities: ['Wood Stove', 'Tesla Solar Panel', 'Starlink WiFi', 'Outdoor Hot Tub', 'Wrap-around Deck'],
    verified: false,
  },
  {
    id: 'p6',
    title: 'Downtown Cozy Studio',
    type: 'Apartment',
    location: '304 Commerce St, Manhattan',
    price: 1950,
    imageUrl: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    reviewsCount: 30,
    landlordName: 'Alice Green',
    landlordAvatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80',
    beds: 1,
    baths: 1,
    sqft: 450,
    description: 'Extremely well-located compact studio, designed for energetic young professionals. Maximized space management with a foldaway Murphy bed, combined washer-dryer unit, and plenty of high-reach hidden shelves. Five minutes from Greenwich subway stations.',
    tags: ['Centrally Located', 'Subway Access', 'Compact'],
    amenities: ['Washer & Dryer', 'Gym Access', 'Secure Entry', 'Subway Proximity', 'Parcel Delivery Room'],
    verified: true,
  },
];
