import { Property } from './types';

export const PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    name: 'The Pavilion Residences',
    location: 'Bangsar, Kuala Lumpur',
    city: 'Kuala Lumpur',
    price: 4500,
    beds: 3,
    baths: 2,
    sizeSqft: 1200,
    stabilityScore: 98,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB8mpJRqVTGq3uqOwye_Lp-kFCYM7bbr8rQYU3_Gk05hVPvx98kD3dq2_M8B4gP93UraByR7eivHwylUzbC3vKlL6a5ng5nlP3KRS8qdeMQ23fWhNfZ898xYRvvZpsuT_vhQPyo9ERP2mBLm5INGY9PYNBhAEw2pjg_wnIs7eihtx7m5xAYPcXjEmu6gckmNxSimmH1CfWRM-EwfORe4nUhF5sOoIX6bxcQR_U4gK1ufErkXipgCbPbejtWhMi8GNfwaZCsM9nnpdo',
    description: 'This luxurious modern apartment interior in Bangsar, Kuala Lumpur features large floor-to-ceiling windows showing a glimpse of lush greenery. Styled in warm neutral tones with designer furnishings, it provides a quiet escape with central city accessibility.',
    amenities: ['24/7 Monitored Security', 'Infinity Swimming Pool', 'Private Elevator Access', 'Built-in Smart Kitchen', 'EV Charging Bays', 'Gymnasium'],
    nearbySites: ['MRT Bangsar (3 min walk)', 'Bangsar Shopping Centre (BSC)', 'Pantai Hospital Kuala Lumpur'],
    type: 'residence'
  },
  {
    id: 'prop-2',
    name: 'Kiara Bay Suite',
    location: 'Mont Kiara, KL',
    city: 'Kuala Lumpur',
    price: 3200,
    beds: 2,
    baths: 2,
    sizeSqft: 950,
    stabilityScore: 95,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAzS6HgegNVNSq-kNBCkV1unix07bXr0iC1InfnET0dzSlbvQoVLDg4Huir7p53rFp3vPO_9iuN8DdLndaX1bDpvzHxAZxlXGdhqhOL63NNgKvWjZy9xiKdIu3Ny23TiVkGd8QCNVH6Bm4egnGy9GkQocGCUhkXS2xRcCvTIobs_jKGZJZIWCkWFmwEh51rBAI1WxEQyjFPuIY0C4RjI3sQIAe2ahpGfiKn-vKGVyozrtge9p8eZOg0gebA8BjHd9RktTXFVNkd4YY',
    description: 'An elegant high-rise condominium in Mont Kiara designed with high architectural standards, featuring glass balconies and integrated vertical gardens. Perfect for professional couples looking for a stable and premium living experience.',
    amenities: ['High-tech Automated Parking', 'Integrated Vertical Gardens', 'Rooftop Lounges', 'Co-working Sky Hub', 'Olympic-size Pool'],
    nearbySites: ['Mont Kiara International School', '1 Mont Kiara Mall', 'Bukit Kiara Federal Park'],
    type: 'suite'
  },
  {
    id: 'prop-3',
    name: 'The Shorefront',
    location: 'George Town, Penang',
    city: 'Penang',
    price: 3800,
    beds: 2,
    baths: 1,
    sizeSqft: 1050,
    stabilityScore: 92,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAW631qobVrjeV64hVOcrINHYhfW8R_PmttVRj0f9aFu419IVTnDGlZWPxPmDTi-ghqghvv6WeWsSqXtoa39TNTjLKI35Tct42k8J59JBNILSpDd2dWcln7hP9pc-TPXmnyC1N5MrlTyHmIKs7wSjGkXkzT2ZeEFUi6OUZqEo-wHkFTrsErXPeG5AcQ38ZLVetdga-EXyCHvfuGhveAvKfbZkk3Y94E3RhX84uk-IgkgOgUR4zZZN3tAFS44-1PA66YrfNm25GZleY',
    description: 'A beautiful, bright beachfront low-density condominium in Penang. Airy design with white walls, light wood flooring, and expansive windows. Direct waterfront views and a serene ocean breeze provide a resort-like sanctuary.',
    amenities: ['Waterfront Deck & Cabanas', 'Private Beach Access', 'Smart Security Guard Network', 'Saltwater Lap Pool', 'Clubhouse Cafe'],
    nearbySites: ['UNESCO Heritage Core (5 min drive)', 'Gurney Drive Promenade', 'Penang Medical Centre'],
    type: 'condo'
  },
  {
    id: 'prop-4',
    name: 'Gurney Paragon Landmark',
    location: 'Gurney Drive, Penang',
    city: 'Penang',
    price: 5200,
    beds: 3,
    baths: 3,
    sizeSqft: 1650,
    stabilityScore: 97,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    description: 'Premier seafront skyscraper living with ultra-spacious layouts, direct shopping mall integration, and spectacular views of the Penang strait.',
    amenities: ['Private Concierge Service', 'Direct Mall Connection', 'Seafront Gym', 'Tennis Courts', 'Jacuzzi Spa Rooms'],
    nearbySites: ['Gurney Plaza Shopping Complex', 'Gleneagles Hospital', 'Pulau Tikus Wet Market'],
    type: 'residence'
  },
  {
    id: 'prop-5',
    name: 'Bukit Bintang Urban Loft',
    location: 'Bukit Bintang, Kuala Lumpur',
    city: 'Kuala Lumpur',
    price: 2600,
    beds: 1,
    baths: 1,
    sizeSqft: 750,
    stabilityScore: 94,
    image: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=800&q=80',
    description: 'Perfectly centered modern living designed for tech professionals, boasting state-of-the-art automation and direct link-bridge connectivity to the MRT/LRT network.',
    amenities: ['Full Home IoT Integration', '24h Delivery Concierge Locker', 'High-Speed Fibre Ready', 'Sky Dining Pavilion'],
    nearbySites: ['Pavilion Kuala Lumpur (5 min walk)', 'MRT Bukit Bintang Station', 'Jalan Alor Street Food Heaven'],
    type: 'apartment'
  },
  {
    id: 'prop-6',
    name: 'Medini Harmony Suite',
    location: 'Iskandar Puteri, Johor',
    city: 'Johor Bahru',
    price: 2100,
    beds: 2,
    baths: 2,
    sizeSqft: 900,
    stabilityScore: 90,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
    description: 'Eco-conscious design focusing on passive cooling technology, solar water heaters, and natural rainwater harvesting systems. Located in the high-growth zone of Medini.',
    amenities: ['Solar Energy Offset Hot Water', 'Premium Wellness Gym', 'Eco-Garden Walkway', 'EV Fast Charging Hub'],
    nearbySites: ['LEGOLAND Malaysia (5 min drive)', 'Gleneagles Medini Hospital', 'Educity Education Hub'],
    type: 'suite'
  }
];
